name: Barber Connect CI/CD Pipeline

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Instalar dependencias
      run: |
        npm ci
        npm install -D ts-node typescript

    # 1. Primero el Build (Ya sabemos que funciona con CI=false)
    - name: Build del Proyecto
      run: CI=false npm run build

    # 2. Pruebas Unitarias (Solo Jest)
    - name: Pruebas Unitarias
      run: npm run test:coverage

    # 3. Pruebas E2E (Playwright - usa la config que ya definimos)
    - name: Instalar Navegadores Playwright
      run: npx playwright install --with-deps

    - name: Pruebas de Integracion y E2E
      run: npx playwright test

    - name: Pruebas de Integracion y E2E
      # Forzamos a que solo busque en la carpeta 'tests' y nada más
      run: npx playwright test tests/ --ignore-snapshots