name: Barber Connect CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Instalar dependencias
      run: |
        npm install
        npm install -D ts-node typescript

    - name: Lint del código
      run: npx eslint src/ --ext .js,.jsx --max-warnings=50 || true

    - name: Build del Proyecto
      run: CI=false npm run build

    - name: Pruebas Unitarias
      run: npm run test:coverage

    - name: Instalar Navegadores Playwright
      run: npx playwright install --with-deps

    - name: Pruebas E2E
      run: npx playwright test tests/
      env:
        BASE_URL: https://proyecto-barber-connect.vercel.app